export interface Book {
  uniqueId: any;
  categoryNo: number;
  category: string;
  author: string;
  name: string;
  content: string;
  loadImg: string;
  hoverImg: string;
  oldPrice: string;
  newPrice: string;
  cart: string;
  wishList: string;
  modal: string;
  title: string;
  sub_title: string;
  language_id: string;
  binding_id: string;
  age_id: string;
  edition_id: string;
  pages: string;
  dimension: string;
  weight: string;
  isbn: string;
  hsncode: string;
  seo_title: string;
  seo_keyword: string;
  seo_description: string;
}
